import { Field, ID, InputType, ObjectType } from 'type-graphql'
import BigInt from 'graphql-bigint'

import { Address } from './address'

/**
 * Represents the payment details of a card to be used for payments. These
 * details are determined by the `card_nonce` generated by `SqPaymentForm`.
 */
@ObjectType()
@InputType('CardInput')
export class Card {
  /** Unique ID for this card. Generated by Square. */
  @Field(() => ID, { nullable: true })
  id?: string

  /** Indicates a card's brand, such as `VISA` or `MASTERCARD`. */
  @Field({ nullable: true })
  cardBrand?: string

  /** The last 4 digits of the card number. */
  @Field({ nullable: true })
  last4?: string

  /** The expiration month of the associated card as an integer between 1 and 12. */
  @Field(() => BigInt, { nullable: true })
  expMonth?: bigint

  /** The four-digit year of the card's expiration date. */
  @Field(() => BigInt, { nullable: true })
  expYear?: bigint

  /** The name of the cardholder. */
  @Field({ nullable: true })
  cardholderName?: string

  /** Represents a physical address. */
  @Field(() => Address, { nullable: true })
  billingAddress?: Address

  /**
   * __Not currently set.__ Intended as a Square-assigned identifier, based
   * on the card number, to identify the card across multiple locations within a
   * single application.
   */
  @Field({ nullable: true })
  fingerprint?: string

  /** Indicates a card's type, such as `CREDIT` or `DEBIT`. */
  @Field({ nullable: true })
  cardType?: string

  /** Indicates a card's prepaid type, such as `NOT_PREPAID` or `PREPAID`. */
  @Field({ nullable: true })
  prepaidType?: string

  /**
   * The first six digits of the card number, known as the Bank Identification Number (BIN). Only the Payments API
   * returns this field.
   */
  @Field({ nullable: true })
  bin?: string
}
